/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Achievement = IDL.Record({
  'studentName' : IDL.Text,
  'subject' : IDL.Text,
  'year' : IDL.Nat,
  'score' : IDL.Nat,
  'grade' : IDL.Nat,
});
export const Review = IDL.Record({
  'starRating' : IDL.Nat,
  'year' : IDL.Nat,
  'reviewText' : IDL.Text,
  'reviewerName' : IDL.Text,
  'grade' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addAchievement' : IDL.Func([Achievement], [], []),
  'addReview' : IDL.Func([Review], [], []),
  'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Achievement = IDL.Record({
    'studentName' : IDL.Text,
    'subject' : IDL.Text,
    'year' : IDL.Nat,
    'score' : IDL.Nat,
    'grade' : IDL.Nat,
  });
  const Review = IDL.Record({
    'starRating' : IDL.Nat,
    'year' : IDL.Nat,
    'reviewText' : IDL.Text,
    'reviewerName' : IDL.Text,
    'grade' : IDL.Nat,
  });
  
  return IDL.Service({
    'addAchievement' : IDL.Func([Achievement], [], []),
    'addReview' : IDL.Func([Review], [], []),
    'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };